# Generated by Django 4.1.5 on 2023-01-08 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroominfo',
            name='studyroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyroom_info', to='studyrooms.studyroom'),
        ),
        migrations.AlterField(
            model_name='studyroominfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyroom_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
